"""
Gap Analysis Domain Model

Represents the outcome of the Gap Analysis process.

Current implementation uses rule-based logic.
Future versions will be generated by the AI Gap Analysis Agent.
"""

from typing import List

from pydantic import BaseModel


class GapAnalysis(BaseModel):

    # ---------------------------------------------------------
    # Overall Assessment
    # ---------------------------------------------------------

    executive_summary: str

    security_maturity: str

    coverage_score: int

    # ---------------------------------------------------------
    # Analysis Results
    # ---------------------------------------------------------

    security_observations: List[str]

    missing_log_sources: List[str]

    missing_detection_use_cases: List[str]

    missing_mitre_coverage: List[str]

    recommendations: List[str]

    detection_roadmap: List[str]

    # ---------------------------------------------------------
    # Knowledge Generated
    # ---------------------------------------------------------

    knowledge_generated: List[str]

    future_ai_usage: str